# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20170221_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='images/posters/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tag',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
