# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20170222_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='films/static/images/posters/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tag',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
