# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20170223_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(max_length=128, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='film',
            name='full_descr',
            field=models.TextField(verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=128, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='films/static/images/posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(max_length=128, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='short_descr',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tag',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tagline',
            field=models.CharField(max_length=128, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год'),
        ),
    ]
