# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20170224_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tag',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
