#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define BUTTON_CONFIRM_ID 1

#define STATIC_NAME_ID 2
#define STATIC_SURNAME_ID 3
#define STATIC_BIRTHDATE_ID 4
#define STATIC_INVESTMENT_ID 5
#define STATIC_PROJECTS_NUMBER_ID 6

#define STATICS_NUM STATIC_PROJECTS_NUMBER_ID - STATIC_NAME_ID + 1

#define EDIT_NAME_ID 7
#define EDIT_SURNAME_ID 8
#define EDIT_BIRTHDATE_ID 9
#define EDIT_INVESTMENT_ID 10
#define EDIT_PROJECTS_NUMBER_ID 11

#define EDITS_NUM EDIT_PROJECTS_NUMBER_ID - EDIT_NAME_ID + 1

#define DLG_STATIC_NAME_ID 12
#define DLG_STATIC_SURNAME_ID 13
#define DLG_STATIC_BIRTHDATE_ID 14
#define DLG_STATIC_INVESTMENT_ID 15
#define DLG_STATIC_PROJECTS_NUMBER_ID 16

#define DLG_STATIC_DELIVERED_NAME_ID 17
#define DLG_STATIC_DELIVERED_SURNAME_ID 18
#define DLG_STATIC_DELIVERED_BIRTHDATE_ID 19
#define DLG_STATIC_DELIVERED_INVESTMENT_ID 20
#define DLG_STATIC_DELIVERED_PROJECTS_NUMBER_ID 21

#define DLG_BUTTON_OK_ID 22

#endif // RESOURCE_H_INCLUDED
