# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва твору:')),
                ('composition', models.TextField(blank=True, verbose_name='Твір:')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('trend', models.CharField(choices=[('DV', 'Detective'), ('FS', 'Fantasy'), ('FC', 'Fantastic'), ('HL', 'Historical')], max_length=2)),
            ],
            options={
                'db_table': 'literary_composition',
            },
        ),
    ]
